person/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^enseignant/$', views.Enseingnat.as_view(), name='Enseingnat'),
    url(r'^emploi/s1/$', views.EtudiantEmploiDutemp.as_view(), name='EtudiantEmploiDutemp'),
    url(r'^emploi/s2/$', views.EtudiantEmploiDutemps2.as_view(), name='EtudiantEmploiDutemps2'),
    url(r'^emploi_prof/s1/$', views.ProfEmploiDutemp.as_view(), name='ProfEmploiDutemp'),
    url(r'^emploi_prof/s2/$', views.ProfEmploiDutemp2.as_view(), name='ProfEmploiDutemps2'),
    url(r'^emploi/examen/s1/$', views.EtudiantEmploiDutempexamens1.as_view(), name='EtudiantEmploiDutempexamens1'),
    url(r'^emploi/examen/s2/$', views.EtudiantEmploiDutempexamens2.as_view(), name='EtudiantEmploiDutempexamens2'),
    url(r'^emploi/pv/s1/$', views.pvs1.as_view(), name='pvs1'),
    url(r'^emploi/pv/s2/$', views.pvs2.as_view(), name='pvs2'),
    url(r'^recours/$', views.Recours.as_view(), name='Recours'),
    url(r'^responsable/$', views.Matiereresponsable.as_view(), name='Matiereresponsable'),
    url(r'^login/enseingnant/$', views.LoginViewEnseingnant.as_view(), name='LoginViewEnseingnant'),
    url(r'^login/$', views.LoginView.as_view(), name='loginacount'),
    url(r'^$', views.Homepage.as_view(), name='Homepage'),
    url(r'^liste_etudiant_l1/$', views.ListEtudiantL1.as_view(), name='ListeEtudiantL1'),
    url(r'^liste_etudiant_l2/$', views.ListEtudiantL2.as_view(), name='ListeEtudiantL2'),
    url(r'^liste_etudiant_l3/$', views.ListEtudiantL3.as_view(), name='ListeEtudiantL3'),
    url(r'^liste_etudiant_m1/$', views.ListEtudiantM1.as_view(), name='ListeEtudiantM1'),
    url(r'^liste_etudiant_m2/$', views.ListEtudiantM2.as_view(), name='ListeEtudiantM2'),
    url(r'^note_etudiant_l1/$', views.NoteEtudiantL1.as_view(), name='NoteEtudiantL1'),
    url(r'^note_etudiant_l2/$', views.NoteEtudiantL2.as_view(), name='NoteEtudiantL2'),
    url(r'^note_etudiant_l3/$', views.NoteEtudiantL3.as_view(), name='NoteEtudiantL3'),
    url(r'^note_etudiant_m1/$', views.NoteEtudiantM1.as_view(), name='NoteEtudiantM1'),
    url(r'^note_etudiant_m2/$', views.NoteEtudiantM2.as_view(), name='NoteEtudiantM2'),
    url(r'^planning_cpc_s1/$', views.PlanningCPCs1.as_view(), name='PlanningCPCs1'),
    url(r'^planning_cpc_s2/$', views.PlanningCPCs2.as_view(), name='PlanningCPCs2'),
    url(r'^planning_pedagogique/$', views.PlanningPedagogique.as_view(), name='PlanningPedagogique'),
    url(r'^planning_surveillence_s1/$', views.PlanningSurveillenceS1.as_view(), name='PlanningSurveillenceS1'),
    url(r'^planning_surveillence_s2/$', views.PlanningSurveillenceS2.as_view(), name='PlanningSurveillenceS2'),
    url(r'^pv_cpc_s1/$', views.PvCpcS1.as_view(), name='PvCpcS1'),
    url(r'^pv_cpc_s2/$', views.PvCpcS2.as_view(), name='PvCpcS2'),
    url(r'^pv_matiere/$', views.PvMatiere.as_view(), name='PvMatiere'),
    url(r'^dep_pv_cpc/$', views.DepPlanningCpc.as_view(), name='DepPlanningCpc'),
    url(r'^recours_note/$', views.RecoursNote.as_view(), name='RecoursNote'),
    url(r'^recours_groupe/$', views.RecoursGroupe.as_view(), name='RecoursGroupe'),
    url(r'^fiche_voeux_master/$', views.FicheDeVoeuxMaster.as_view(), name='FicheDeVoeuxMaster'),
    url(r'^document/$', views.DocaSigner, name='Document'),
]

pfe/urls.py
from django.conf.urls.static import static
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'', include(('person.urls',"pfe"), namespace='pfe')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', logout,{'next_page':'/'}),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

person/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class person(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)

    class Meta:
        abstract = True

ANNE_CHOICES = (
        (1, 'L1'),
        (2, 'L2'),
        (3, 'L3'),
        (4, 'M1 SITW'),
        (4, 'M1 RSD'),
        (4, 'M1 RESIM'),
        (4, 'M1 ADSI'),
        (4, 'M1 IIPE'),
        (5, 'M2 SITW'),
        (5, 'M2 RSD'),
        (5, 'M2 RESIM'),
        (5, 'M2 ADSI'),
        (5, 'M2 IIPE'),
        (10, 'D'),
)
SEMESTRE_CHOICES = (('1','s1'),('2','s2'))



class etudiant(person):
    parcour = models.IntegerField(choices=ANNE_CHOICES)
    numero = models.IntegerField(unique=True)
    def __str__(self):
        return self.nom



GRADE_CHOICES = (
        ('P', 'PES'),
        ('A', 'ASS'),
        ('M', 'MAB'),
        ('M', 'MAA'),
        ('M', 'MCB'),
        ('M', 'MCA'),
        ('P', 'PROF'),
)
class roles(models.Model):
    role = models.CharField(max_length=255)
    def __str__(self):
        return self.role

class Adminstration(person):
    roles = models.ForeignKey(roles,on_delete=models.CASCADE)
    grade = models.CharField(max_length=1, choices=GRADE_CHOICES)

    def __str__(self):
        return self.nom

class Secretaire(person):
    pass


class matierre(models.Model):
    matierre = models.CharField(max_length=255)
    parcour = models.IntegerField(choices=ANNE_CHOICES)
    semstre = models.CharField(choices=SEMESTRE_CHOICES, max_length=1)
    coef = models.IntegerField()
    responsable = models.OneToOneField(Adminstration,on_delete=models.CASCADE)
    enseignant = models.ManyToManyField(Adminstration,related_name="prof")

    def __str__(self):
        return self.matierre


class note(models.Model):
    note_td = models.FloatField()
    note_tp = models.FloatField()
    note_cour = models.FloatField()
    note_examen = models.FloatField()
    moyenne = models.FloatField()
    matierre = models.OneToOneField(matierre,on_delete=models.CASCADE)
    etudiant = models.OneToOneField(etudiant,on_delete=models.CASCADE)

    def __str__(self):
        return self.etudiant.nom + '/' + self.matierre.matierre

    class Meta:
        unique_together = ('matierre', 'etudiant')

RECOURS_CHOICES = (
        ('1', 'changement de groupe'),
        ('2', 'changement des notes'),
)
ETATS_CHOICES = (
        ('1', 'ACCEPTÉ'),
        ('2', 'REFFUSÉ'),
        ('3', 'PAS DE DESSISION'),
)


class recours(models.Model):
    etudiant = models.ForeignKey(etudiant,on_delete=models.CASCADE)
    recours = models.CharField(choices=RECOURS_CHOICES, max_length=1)
    remarque = models.TextField()
    accepte = models.CharField(max_length=1,choices=ETATS_CHOICES)
    def __str__(self):
        return self.etudiant.nom

class Cpc(models.Model):
    semsetre = models.CharField(max_length=1,choices=SEMESTRE_CHOICES)
    parcour = models.IntegerField(choices=ANNE_CHOICES)
    responsable = models.OneToOneField(Adminstration,related_name="responsable",on_delete=models.CASCADE)
    date_cpc = models.CharField(max_length=20)
    def __str__(self):
        return str(self.get_parcour_display()) + '/' + str(self.get_semsetre_display())


class DocSigner(models.Model):
    nom_doc = models.CharField(max_length=200)
    url_doc = models.FileField(null=True, blank=True)
    destination = models.ForeignKey(Adminstration,on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.nom_doc)
#etudiant
# nom et prenom  parcours anne en haut
# emploi du temp de semstre s1 et s2 static
# emploi du temp examen static
# listes des pv s1 et s2
# liste des profs responsable de la matiere
# la liste des recours

# enseignant
# nom prenom grade et profile
# filtrer les pv par anné et matiere
# emploi du temp static

#adjoint post graduation
# dossier dossier des doctorant static

# chef scolaritè:
# listed des etudiant pv de soutnance de chaque etudiant
# pv de delibiration pv #s1 et s2
# les document static chaque etudiant avec groupe

#responsable cpc
#pv cpc documetn static semstre
#pv matiere par module et semstre
#planing
# les recours

#responsable de domain
# voir les pv des matiere

#adjoin pedagogique
#planing de surviallance
#planing de soutnance

#chef de departement
#planing de doctorat
#document a signer


#resposable ed matiere
#voire et envoyè pv matiere au resposnsable d'ènutié
#

#responsable d'enitè
# voir et envoyè le pv d'enutè

#secretaire/
#consulte le planing de soutnance
#consulter pv matiere
#consulter planing cpc
#voir les justificatif absence
#voir les justificatif recour
#voir les fiche des voeux de matiere

person/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse, HttpResponseRedirect, request

from .models import Adminstration

class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Numero'}))


class Enseingantloginform(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':"Nom de l'utilisateur"}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Mot de passe'}))

person/templates/person/ens_emploi2.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}

    {% block loadcontent %}
        <img src="{% static '/img/emploi.png' %}" alt="">
    {% endblock loadcontent %}
{% endblock %}

person/templates/person/fiche_de_voeux_master.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}

    {% block loadcontent %}
        <img src="{% static '/img/fiche_de_voeux_master.png' %}" alt="">
    {% endblock loadcontent %}
{% endblock %}

person/templates/person/listeDocument.html
{% extends 'person/enseingant.html' %}



{% block content %}
<div class="container">
    <br>
    <table class="table table-hover">
    <thead>
      <tr>
        <th>Fichier</th>
        <th>Lien Telechargement</th>
        <th>source</th>
      </tr>
    </thead>
    <tbody>
    {% for n in doc %}
    {%if n.destination.roles.role == 'Chef departement'%}
      <tr>
        <td>{{ n.nom_doc}}</td>
        <td><a href="/media/{{ n.url_doc }}">telecharger</a></td>
        <td>{{ n.destination.roles.role }}</td>
      </tr>
    {%endif%}
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

person/templates/person/liste_etudiant.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}


<div id="right_bar">
<table>
    <tr>
        <th>Nom</th>
        <th>Prenom</th>
    </tr>

        {% for object in object_list %}
    <tr>
           <th>{{ object.nom }}</th>
           <th>{{ object.prenom }}</th>
    </tr>
        {% endfor %}

</table>
</div>
{% endblock %}

person/templates/person/login.html
{% extends 'base.html' %}
{% block id %}
id="login"
{% endblock %}
{% block content %}
<div id="loginform" class="uk-inline">
<div class="uk-position-center uk-card uk-card-default uk-card-body login_css ">
    <div>
        <h3>Authentification</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <div>
                <input class="basic_css" type="submit">
            </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

person/templates/person/note_etudiant.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}


<div id="right_bar">
<table>
    <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Matiere</th>
        <th>Note TD</th>
        <th>Note TP</th>
        <th>Note Cours</th>
        <th>Note Examen</th>
        <th>Moyenne</th>
    </tr>

        {% for object in object_list %}
    <tr>
           <th>{{ object.etudiant.nom }}</th>
           <th>{{ object.etudiant.prenom }}</th>
           <th>{{ object.matierre.matierre }}</th>
           <th>{{ object.note_td }}</th>
           <th>{{ object.note_tp }}</th>
           <th>{{ object.note_cour }}</th>
           <th>{{ object.note_examen }}</th>
           <th>{{ object.moyenne }}</th>
    </tr>
        {% endfor %}

</table>
</div>
{% endblock %}

person/templates/person/planning_cpc_s1.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}


<div id="right_bar">
<table>
    <tr>
        <th>CPC</th>
        <th>Date</th>
    </tr>
    <tr>
        <th>CPC 1</th>
        <th>19/10/2018</th>
    </tr>
    <tr>
        <th>CPC 2</th>
        <th>18/11/2018</th>
    </tr>
    <tr>
        <th>CPC 3</th>
        <th>29/11/2018</th>
    </tr>
    <tr>
        <th>CPC 4</th>
        <th>15/12/2018</th>
    </tr>

</table>
</div>
{% endblock %}

person/templates/person/planning_surveillence_s2.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}

    {% block loadcontent %}
        <img src="{% static '/img/emploi.png' %}" alt="">
    {% endblock loadcontent %}
{% endblock %}

person/templates/person/pv_cpc_s2.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}

    {% block loadcontent %}
        <h1>CPC 1</h1>
        <img src="{% static '/img/pvCpcP1.JPG' %}" alt="">
        <img src="{% static '/img/pvCpcP2.JPG' %}" alt="">
        <h1>CPC 2</h1>
        <img src="{% static '/img/pvCpcP1.JPG' %}" alt="">
        <img src="{% static '/img/pvCpcP2.JPG' %}" alt="">
        <h1>CPC 3</h1>
        <img src="{% static '/img/pvCpcP1.JPG' %}" alt="">
        <img src="{% static '/img/pvCpcP2.JPG' %}" alt="">
        <h1>CPC 4</h1>
        <img src="{% static '/img/pvCpcP1.JPG' %}" alt="">
        <img src="{% static '/img/pvCpcP2.JPG' %}" alt="">
    {% endblock loadcontent %}
{% endblock %}

person/templates/person/pvs1.html
{% extends 'person/etudiant_dashboard.html' %}
{% load  static %}

{% block content %}


<div id="right_bar">
<table>
    <tr>
        <th>Matiere</th>
        <th>Note TD</th>
        <th>Note TP</th>
        <th>Note COURS</th>
        <th>Note EXAMEN</th>
        <th>Coef</th>
        <th>MOY</th>
    </tr>

        {% for object in object_list %}
    <tr>
           <th>{{ object.matierre.matierre }}</th>
           <th>{{ object.note_td }}</th>
           <th>{{ object.note_tp }}</th>
           <th>{{ object.note_cour }}</th>
           <th>{{ object.note_examen }}</th>
           <th>{{ object.matierre.coef }}</th>
           <th>{{ object.moyenne }}</th>
    </tr>
        {% endfor %}

</table>
</div>
{% endblock %}

person/templates/person/recours.html
{% extends 'person/etudiant_dashboard.html'%}
{% load  static %}

{% block content %}

<div id="right_bar">
<table>
    <tr>
        <th>Type</th>
        <th>Etat</th>
    </tr>

        {% for object in object_list %}
    <tr>
        <th>{{ object.get_recours_display }}</th>
        <th>{{ object.get_accepte_display }}</th>
    </tr>
        {% endfor %}

</table>
</div>
{% endblock %}

person/templates/person/recours_groupe.html
{% extends 'person/enseingant.html' %}
{% load  static %}

{% block content %}

<div id="right_bar">
<table>
    <tr>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Parcour</th>
        <th>Remarque</th>
    </tr>

        {% for object in object_list %}
    <tr>
        <th>{{ object.etudiant.nom }}</th>
        <th>{{ object.etudiant.prenom }}</th>
        <th>{{ object.etudiant.get_parcour_display }}</th>
        <th>{{ object.remarque }}</th>
    </tr>
        {% endfor %}

</table>
</div>
{% endblock %}

person/templates/person/respoonsable.html
{% extends 'person/etudiant_dashboard.html'%}
{% load  static %}

{% block content %}

<div id="right_bar">
<h1>Reponsable des matiere s1</h1>
<table>
    <tr>
        <th>Matiere</th>
        <th>Responsable</th>
    </tr>
        {% for object in s1%}
    <tr>
        <th>{{ object.matierre }}</th>
        <th>{{ object.responsable}}</th>
    </tr>
        {% endfor %}
</table>
<h1>Reponsable des matiere s2</h1>
<table>
    <tr>
        <th>Matiere</th>
        <th>Responsable</th>
    </tr>
        {% for object in s2%}
    <tr>
        <th>{{ object.matierre }}</th>
        <th>{{ object.responsable}}</th>
    </tr>
        {% endfor %}
</table>

</div>
{% endblock %}